development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dwarf
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dwarf_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dwarf
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
